### ISSUE TITLE
Sorting on version number is not correct (starting with TAS 10.0.0)

### ISSUE THREAD

**Issue by Ysbrand** [danmed/TasmoBackupV1#67]
Hi,

When I sort ob version number it seems that it is not based on numeric order:
10.x.x
8.x
9.x

Apparently the sorting is based on alphanumeric (instead of numeric).

![TAS-Versions](https://user-images.githubusercontent.com/16001552/139389669-12729632-a8e4-41b3-8275-5ddc9e2872ef.JPG)

**Comment by patrickdk77** [comment]
Yes, I'll have to look at it, it's very troublesom to do though, cause you cannot do it via numeric cause it's not a proper number.

**Comment by patrickdk77** [comment]
fixed in 1.04.24

**Comment by Ysbrand** [comment]
Thanks for looking into this some promptly.
I'm now running the new version (Current version: 1.04.24), but the issue remains the same

**Comment by patrickdk77** [comment]
likely a browser caching issue, try a control-f5 or whatever it is on macs to flush the cache.

**Comment by Ysbrand** [comment]
Sorry, tried that already, as well as a complete restart of the host HA is running on.

![image](https://user-images.githubusercontent.com/16001552/139548241-b515e84f-521e-4601-885c-7174710f8a47.png)

**Comment by patrickdk77** [comment]
![image](https://user-images.githubusercontent.com/8078633/139556675-473d5adb-13ba-4be5-8a16-65b072b3fb88.png)
Not sure, I have tried but I cannot reproduce the issue.
Check the version in the lower right corner.

**Comment by Ysbrand** [comment]
Hmm, looks like you are running a higher version: 1.04.25


![image](https://user-images.githubusercontent.com/16001552/139557870-8dd2717e-a321-4e10-acfc-8eeb4aa63934.png)

The change list showed that the fix was included in 1.04.24, but maybe I misread this:
![image](https://user-images.githubusercontent.com/16001552/139557902-4790ef32-c87a-4ded-990b-c420083c5af1.png)



I also noticed that the logs is full of these kind of messages, not sure if that is related, or should I open anew issue?

`[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 652"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 652"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651"
[30-Oct-2021 22:08:15] WARNING: [pool www] child 2060 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651"
2021/10/30 22:08:15 [error] 63#63: *533 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 652PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 652PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 652PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 648PHP message: PHP Notice:  Undefined variable: name in /var/www/html/lib/functions.inc.php on line 650PHP message: PHP Notice:  Undefined variable: version in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: mac in /var/www/html/lib/functions.inc.php on line 651PHP message: PHP Notice:  Undefined variable: name in /var/`

**Comment by patrickdk77** [comment]
Those are just cause I have been doing a lot of javascript programming and didn't use isset in those places, those only happen when it does a scan and the correct thing happens. I've fixed it in the code for the next release.

You can update and see, but yes the sorting code was fixed in 1.04.24 and hasn't been touched, the fixes in 1.04.25 and 1.04.26 has to do with wled.

MIght be that version didn't release properly and the sorting code did actually get into the file release file, so do update and try.

**Comment by Ysbrand** [comment]
Still the same issue. I guess its not that important to spend too much time on. Appreciate the effort anyway :)
